---
- name: Install DB
  hosts: db
  become: true
  tasks:
          - name: Ensure postgresql package is present
            docker_image:
                    name: postgres

          - name: Install docker-compose
            apt:
                    name: docker-compose
                    state: present

          - name: Create path for docker-compose
            file:
                    path: /etc/docker-db
                    state: directory

          - name: Create path mount
            file:
                    path: /etc/postgres
                    state: directory

          - name: Copy file to remote host
            copy:
                    src: ./docker-compose.yml
                    dest: /etc/docker-db

          - name: Run docker-compose
            shell: "docker-compose -f /etc/docker-db/docker-compose.yml up"

