---
- name: Import playbook site1-2
  import_playbook: createnginx-site.yml
- name: Install HaProxy, create haproxy balance
  hosts: vm1
  become: true
  tasks:
          - name: Install HAProxy
            docker_image:
                    name: haproxy

          - name: Create directory balance
            file:
                    path: /etc/balance
                    state: directory

          - copy:
                  src: ./haproxy
                  dest: /etc/balance/haproxy

          - copy:
                  src: ./Dockerfile-haproxy
                  dest: /etc/balance/Dockerfile

          - name: Build docker image balance
            docker_image:
                    name: balance-haproxy
                    build:
                            path: /etc/balance
                    state: present

          - name: Run Docker Container balance
            docker_container:
                    name: balance
                    image: balance
                    state: started
                    recreate: yes
                    ports:
                            - "80:80"

          - name: Delete file
            file:
                    path: /etc/balance
                    state: absent
