---
- name: Install Docker in Local Machine
  hosts: all
  become: true
  tasks:
          - name: Install packages
            apt:
                    name: "{{ item }}"
                    state: present
            loop:
                    - apt-transport-https
                    - ca-certificates
                    - curl
                    - software-properties-common

          - name: Add key GPG
            shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'

          - name: Add repository Docker
            shell: 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
'
          - name: Apt update
            apt:
                    update_cache: yes

          - name: Install Docker-ce
            apt:
                    name: docker-ce
                    state: present

          - name: Add zhidkovd in group docker
            shell: 'usermod -aG docker zhidkovd'



            
